# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/cryptroot";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/4ae05a3e-1e33-4303-9c54-b54a45b302ff";
  };

  boot.initrd.luks.devices."cryptswap" = {
    device = "/dev/disk/by-uuid/af3285ab-762e-46b6-a624-a973b579700e";
    keyFile = "/crypto_keyfile.bin";
    allowDiscards = true;
  };

  # Include the keyfile in initrd
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = "/crypto_keyfile.bin";
  };

  # Resume from encrypted swap (optional, enables hibernation)
  boot.resumeDevice = "/dev/mapper/cryptswap";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1059-3FEE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/mapper/cryptswap"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
