# Key philosophy:
# - Ctrl-based shortcuts work on top of vim-style commands
# - Space is the leader key for vim-style commands
# - which-key shows available commands as you type
# - Everything is discoverable - no memorization required
# - Arrow keys work, but hjkl alternatives are always available
#
# File structure:
# - neovim.nix: Main config (this file) - defines plugins
# - lua/settings.lua: Basic vim settings
# - lua/plugins/*.lua: Plugin configurations
# - lua/keybindings.lua: All keybindings
# - lua/keys.lua: Generated from central keybindings/

{ pkgs-unstable, lib, ... }:

let
  # Import central keybindings
  central = import ../../keybindings { inherit lib; };
  keys = central.neovim;

  # Helper function to convert Nix attrset to Lua table
  toLuaTable =
    attrs:
    let
      pairs = lib.mapAttrsToList (k: v: "  ${k} = '${v}'") attrs;
    in
    "{\n" + (lib.concatStringsSep ",\n" pairs) + "\n}";

  # Generate keys.lua content from central keybindings
  keysLuaContent = ''
    -- Auto-generated from central keybindings/
    -- DO NOT EDIT THIS FILE DIRECTLY - edit home/keybindings/ instead

    return {
      tabs = ${toLuaTable keys.tabs},
      windows = ${toLuaTable keys.windows},
      panels = ${toLuaTable keys.panels},
      navigation = ${toLuaTable keys.navigation},
      editing = ${toLuaTable keys.editing},
      folding = ${toLuaTable keys.folding},
      view = ${toLuaTable keys.view},
      ai = ${toLuaTable keys.ai},
      help = ${toLuaTable keys.help},
      vimApps = ${toLuaTable keys.vimApps},
    }
  '';
in
{
  programs.neovim = {
    viAlias = true;
    vimAlias = true;
    defaultEditor = true;

    plugins = with pkgs-unstable.vimPlugins; [
      # ========================================
      # Core plugins for VSCode-like experience
      # ========================================

      # File explorer (like VSCode sidebar)
      nvim-tree-lua
      nvim-web-devicons

      # Fuzzy finder (like Ctrl+P in VSCode)
      telescope-nvim
      plenary-nvim
      telescope-fzf-native-nvim

      # Which-key - shows keybindings as you type (game changer!)
      which-key-nvim

      # Status line
      lualine-nvim

      # Buffer line (tabs at top, like VSCode)
      bufferline-nvim

      # Git signs in gutter (like VSCode)
      gitsigns-nvim

      # Git integration
      lazygit-nvim
      taskwiki

      # ========================================
      # Editor enhancements
      # ========================================

      # Syntax highlighting
      nvim-treesitter.withAllGrammars

      # Auto pairs for brackets
      nvim-autopairs

      # Comment toggle (gcc, gc in visual)
      comment-nvim

      # Surround text objects (quotes, brackets)
      nvim-surround

      # Indent guides (like VSCode)
      indent-blankline-nvim

      # Better escape (jj to exit insert mode)
      better-escape-nvim

      # Smooth scrolling
      neoscroll-nvim

      # ========================================
      # LSP & Completion (like VSCode IntelliSense)
      # ========================================

      # LSP configuration
      nvim-lspconfig

      # Nice LSP UI
      lspsaga-nvim

      # Completion engine
      nvim-cmp
      cmp-nvim-lsp
      cmp-buffer
      cmp-path
      cmp-cmdline

      # Snippets
      luasnip
      cmp_luasnip
      friendly-snippets

      # ========================================
      # AI / Copilot
      # ========================================

      # GitHub Copilot
      copilot-vim
      copilot-lua
      copilot-cmp

      # ========================================
      # UI Improvements
      # ========================================

      # Notifications
      nvim-notify

      # Better UI for inputs/selects
      dressing-nvim

      # Terminal integration
      toggleterm-nvim

      # Dashboard on startup
      alpha-nvim
    ];

    extraLuaConfig = ''
      -- Load modular configuration files
      -- Each module handles a specific aspect of the config

      -- Basic vim settings
      require('settings')

      -- Plugin configurations
      require('plugins.ui')         -- bufferline, lualine, alpha, notify, dressing
      require('plugins.editor')     -- treesitter, autopairs, comment, surround, indent-blankline, better-escape, neoscroll
      require('plugins.explorer')   -- nvim-tree
      require('plugins.finder')     -- telescope
      require('plugins.git')        -- gitsigns
      require('plugins.terminal')   -- toggleterm
      require('plugins.lsp')        -- lspconfig, lspsaga, cmp

      -- Keybindings (VSCode-like + vim)
      require('keybindings')
    '';
  };

  # Generate keys.lua from central keybindings
  home.file.".config/nvim/lua/keys.lua".text = keysLuaContent;

  # Copy lua configuration files to nvim config directory
  home.file.".config/nvim/lua/settings.lua".source = ./lua/settings.lua;
  home.file.".config/nvim/lua/keybindings.lua".source = ./lua/keybindings.lua;
  home.file.".config/nvim/lua/plugins/ui.lua".source = ./lua/plugins/ui.lua;
  home.file.".config/nvim/lua/plugins/editor.lua".source = ./lua/plugins/editor.lua;
  home.file.".config/nvim/lua/plugins/explorer.lua".source = ./lua/plugins/explorer.lua;
  home.file.".config/nvim/lua/plugins/finder.lua".source = ./lua/plugins/finder.lua;
  home.file.".config/nvim/lua/plugins/git.lua".source = ./lua/plugins/git.lua;
  home.file.".config/nvim/lua/plugins/terminal.lua".source = ./lua/plugins/terminal.lua;
  home.file.".config/nvim/lua/plugins/lsp.lua".source = ./lua/plugins/lsp.lua;
}
